---
title: "Coffee Analysis"
author: "AB"
date: "`r format(Sys.Date(), '%d/%m/%Y')`"
output: html_document
---

```{r setup, include=FALSE, message=F}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE,
                      fig.align = "center", fig.width = 9, fig.retina = 3)

library(dplyr)
library(tidyr)
library(ggplot2)
library(scales)
library(lubridate)

theme_set(theme_light())

brewmaster_raw <- readr::read_csv("../data/brewmaster2_latest.csv")
new_grinder <- as.Date("2020-08-18")
brewmaster_raw <- 
  brewmaster_raw %>%
  filter(createdAt > new_grinder, id != "TOljBAo2Uo")
```



```{r tidy functions, echo = F}
my_brew_data_time <- 
  function(x, 
           split = ";", 
           pad_length = NULL, 
           beginning_time = 8, 
           beginning_tol = 0.5,
           stall_tol = 0.05,
           change_lag = 2){
    
    split_data <- as.numeric(unlist(strsplit(x, split =  split)))
    
    # Want to remove any spikes at the beginning of the pour
    beginning_vals <- 1:round(beginning_time/0.2)
    beginning_outliers <- which(abs(split_data[beginning_vals]) >= beginning_tol)
    if (length(beginning_outliers) > 0)
      split_data[beginning_vals][beginning_outliers] <- 0
    
    
    lag_n <- diff(split_data, lag = change_lag)
    first_flow <- min(which(lag_n > beginning_tol))
    
    lag_n_backwards <- diff(rev(split_data), lag = change_lag)
    last_flow <- min(which(lag_n_backwards < -stall_tol))
    last_flow <- length(split_data) - last_flow
    
    if (last_flow > first_flow) {
      split_data[last_flow:length(split_data)] <- NA
    }else{
      last_flow <- length(split_data)
    }

    if (!is.null(pad_length))
      split_data <- c(split_data, rep(NA, pad_length - length(split_data)))
    
    split_data <- c(split_data, first_flow, last_flow)

    names(split_data) <- c(paste("t",1:(length(split_data) - 2), sep = "_"),
                           "estimated_first_flow", "estimated_last_flow")
    return(split_data)
  }

# my_brew_data_series <- function(.data, col_name, ...){
#   col_name <- as_label(enquo(col_name))
#   .data %>%
#     bind_cols(do.call(bind_rows, lapply(.data[[col_name]], my_brew_data_time, ...))) %>%
#     select(-col_name)
# }

my_brew_data_series <- function(.data, col_name, ...){
  col_name <- as_label(enquo(col_name))
  .data %>%
    bind_cols(
      lapply(.data[[col_name]], my_brew_data_time, ...) %>%
        bind_rows()
    ) %>%
    select(-col_name)
}

my_brew_data_json <- function(.data, col_name, decaf = FALSE){
  col_name <- as_label(enquo(col_name))
  .data %>%
    bind_cols(
      lapply(.data[[col_name]], function(x) jsonlite::fromJSON(gsub("”|“", '"', x))) %>%
        bind_rows()) %>%
    select(-col_name)
}
```

```{r, eval = F, echo =F}
coffee_tidy_old <- 
  brewmaster_raw %>% 
  # Separate out name
  separate(name, sep = ",", into = c("type", "roastery", "origin")) %>%
  # parse json column
  my_brew_data_json(note) %>%
  # tidy decaf column
  mutate(decaf = case_when(is.na(decaf) ~ F, T ~ T)) %>%
  # process brew data
  my_brew_data_series(`brew data`,
                      stall_tol = 0.05,
                      change_lag = 2) %>%
  # reshape data to have weight and time in a single column
  pivot_longer(cols = starts_with("t_"),
               names_to = "time", values_to = "weight") %>%
  # tidy columns
  mutate(time = as.numeric(gsub("t_", "", time)) * 0.2,
         weight = as.numeric(weight),
         createdAt = as_date(createdAt), 
         roast_date = as_date(roast_date),
         age = createdAt - roast_date, 
         ratio = `total weight`/dose %>%
  # choose columns to keep
  select(id, createdAt, type, roastery, roast_date, origin, age, grind, dose,  
         total_time = `total time`, total_weight = `total weight`,
         ratio, time, weight, decaf, mean_flow = `average flowrate`, 
         estimated_begin, estimated_end)
```


## Wrangle Data

```{r wrangle data}
espresso_summary <- 
  brewmaster_raw %>% 
  # Separate out name
  separate(name, sep = ",", into = c("type", "roastery", "origin")) %>%
  # parse json column
  my_brew_data_json(note) %>%
  # tidy decaf column
  mutate(decaf = case_when(is.na(decaf) ~ F, T ~ T)) %>%
  # tidy columns
  mutate(createdAt = as_date(createdAt), 
         roast_date = as_date(roast_date),
         age = createdAt - roast_date, ratio = `total weight`/dose) %>%
  # rename columns
  rename(total_time = `total time`, total_weight = `total weight`,
         mean_flow = `average flowrate`, brew_data = `brew data`)


flow_data <- 
  espresso_summary  %>%
  my_brew_data_series(brew_data, 
                      stall_tol = 0.1,
                      change_lag = 2) %>%
  # reshape data to have weight and time in a single column
  pivot_longer(cols = starts_with("t_"),
               names_to = "time", values_to = "weight") %>%
  # parse time and calc times
  mutate_if(is.character, trimws) %>%
  mutate(time = as.numeric(gsub("t_", "", time)) * 0.2,
         weight = as.numeric(weight),
         estimated_begin = estimated_first_flow * 0.2,
         estimated_end = estimated_last_flow * 0.2,
         flow_rate = (weight - dplyr::lag(weight))/0.2) %>%
  group_by(id) %>%
  mutate(smooth_flow = zoo::rollapply(flow_rate, 11, mean, fill = NA, na.rm = TRUE)) 
```

## Weight Over Time

```{r}
flow_data %>%
  filter(!decaf) %>%
  ggplot(aes(x = time, y = weight, group = id, colour = grind)) +
  geom_line() +
  scale_color_continuous(type = "viridis") +
  scale_x_continuous(labels = function(x)paste0(x,"s")) +
  scale_y_continuous("yield", labels = function(x)paste0(x, "g"))
```

## Summary Stats

```{r}
coffee_summary_extra <- 
  flow_data %>%
  group_by(id, grind, origin, roastery, dose, age) %>%
  summarise(max_entry = which.max(is.na(weight)),
            final_weight = max(weight, na.rm = T),
            estimated_begin = min(estimated_begin)) %>%
  mutate(final_time = max_entry * 0.2,
         age = as.numeric(age), 
         ratio = final_weight/dose) %>%
  filter(final_weight > 20, final_weight < 50)
```

```{r}
coffee_summary_extra %>%
  ggplot(aes(final_time, grind, shape = origin, colour = age, size = ratio)) +
  geom_jitter(width = 0, height = 0.075) +
  scale_color_continuous(type = "viridis", labels = function(x) paste0(x, " dayss")) +
  guides(size = guide_legend(reverse = TRUE)) +
  scale_x_continuous("time", labels = function(x) paste0(x, "s"))
```


```{r}
coffee_summary_extra %>%
  ggplot(aes(dose, final_weight, colour = origin)) +
  geom_point() +
  scale_x_continuous("dose", labels = function(x)paste0(x, "g")) +
  scale_y_continuous("yield", labels = function(x)paste0(x, "g"))
```


```{r}
# coffee_summary_extra %>%
#   ggplot(aes(ratio, final_time, colour = origin, size = grind)) +
#   geom_point() 

coffee_summary_extra %>%
  ggplot(aes(final_time, ratio, colour = grind, size = age)) +
  scale_color_continuous(type = "viridis") +
  geom_point() +
  facet_wrap(~origin) +
  guides(size = guide_legend(reverse = TRUE)) +
  scale_size_continuous(labels = function(x) paste0(x, " days")) +
  scale_x_continuous("time", labels = function(x) paste0(x, "s"))
```



```{r}
library(knitr)
library(kableExtra)
coffee_summary_extra %>%
  select(roastery, origin, age, grind, dose, yield = final_weight, ratio, time = final_time) %>%
  mutate(ratio = round(ratio, 2)) %>%
  group_by(roastery, origin) %>%
  summarise(mean_grind = mean(grind), mean_dose = mean(dose), mean_yield = mean(yield),
            mean_ratio = mean(ratio), mean_time = mean(time)) %>%
  arrange(roastery, origin) %>%
  kable(digits = 2) %>%
  kable_styling() 
```



# Flow Rate

```{r}
flow_data %>%
  filter(smooth_flow > -2, smooth_flow < 8) %>%
  mutate(age = as.numeric(age)) %>%
  # # group_by(id, grind, origin, roastery, dose, age) %>%
  # mutate(flow_rate = (weight - dplyr::lag(weight))/0.2) %>%
  # group_by(id) %>%
  # mutate(smooth_flow = zoo::rollapply(flow, 11, mean, fill = NA, na.rm = TRUE)) %>%
  ggplot() +
  geom_line(aes(x = time, y = smooth_flow, group = id, colour = age)) +
  scale_color_continuous(type = "viridis") +
  scale_y_continuous("flow rate", labels = function(x) paste0(x, "g/s")) +
  geom_smooth(aes(x = time, y = smooth_flow), colour = "red")
```


## Single Batch Over Time

```{r, echo = F, eval = F}
coffee_summary_extra %>%
  filter(origin == "Brazil", roastery == "Full Circle", grind > 3.4) %>%
  ggplot(aes(x = age, y = grind, size = ratio, colour = final_time)) +
  geom_jitter(width = 0, height = 0.01, alpha = 0.9) +
  scale_color_continuous(type = "viridis", labels = scales::number_format(suffix = "s")) +
  guides(size = guide_legend(reverse = TRUE)) +
  labs(x = "Days Since Roast", y = "Grind Setting", size = "Ratio", colour = "Shot Time")

# ggsave("figures/coffee_2020-09-03.png", width = 7, height = 4)
```




```{r, fig.align='center', out.width="100%"}
single_batch <- 
  coffee_summary_extra %>%
  filter(origin == "Brazil", roastery == "Full Circle", grind > 3.4) %>%
  ggplot(aes(x = age, y = grind, size = ratio, colour = final_time, 
             group = 1, text = paste0("Dose: ", dose, 
                                      "<br>Yield: ", final_weight,
                                      "<br>Ratio: ", round(ratio, 2),
                                      "<br>Time: ", final_time))) +
  geom_jitter(width = 0, height = 0.01, alpha = 0.9) +
  scale_color_continuous(type = "viridis", labels = scales::number_format(suffix = "s")) +
  guides(size = guide_legend(reverse = TRUE)) +
  labs(x = "Days Since Roast", y = "Grind Setting", size = "Ratio", colour = "Shot Time")

plotly::ggplotly(single_batch, tooltip = "text")
```

